import { Ticket, ITicket, TicketCategory, TicketPriority, TicketStatus, EscalationStatus } from '../models/Ticket';
import { Feedback } from '../models/Feedback';
import { memoryStore, MemoryTicket } from '../models/memoryStore';
import { isMongoConnected } from '../config/database';
import { generateTicketId } from '../utils/ticketIdGenerator';

export class TicketService {
  /**
   * Creates a new ticket
   */
  public static async createTicket(data: {
    category: TicketCategory;
    priority: TicketPriority;
    title: string;
    description: string;
    summary: string;
    department?: string;
    customerId?: string;
    customerName?: string;
    customerEmail?: string;
    recommendedAction?: string;
    extractedEntities?: {
      orderId?: string;
      transactionId?: string;
      amount?: string;
      date?: string;
      productName?: string;
    };
    shouldEscalate?: boolean;
  }) {
    const ticketId = generateTicketId();
    const department = data.department || 'General Support';
    const escalationStatus: EscalationStatus = data.shouldEscalate ? 'Escalated' : 'None';

    const timeline = [
      {
        timestamp: new Date(),
        event: 'Ticket automatically generated by Nexura AI Complaint Intelligence',
        performedBy: 'Nexura AI',
        note: `Intent analyzed with ${data.priority} Priority under ${data.category}`,
      },
    ];

    if (data.shouldEscalate) {
      timeline.push({
        timestamp: new Date(),
        event: 'Auto-escalated to Human Support Specialist',
        performedBy: 'Nexura AI Escalation Rule',
        note: 'Escalated due to high-urgency complaint characteristics',
      });
    }

    if (isMongoConnected) {
      const ticket = new Ticket({
        ticketId,
        customerId: data.customerId || 'CUST-DEMO-01',
        customerName: data.customerName || 'Alex Mercer',
        customerEmail: data.customerEmail || 'alex.mercer@example.com',
        category: data.category,
        priority: data.priority,
        title: data.title,
        description: data.description,
        summary: data.summary,
        department,
        status: 'Open',
        escalationStatus,
        recommendedAction: data.recommendedAction || 'Review issue details and verify with backend systems.',
        extractedEntities: data.extractedEntities,
        timeline,
      });
      return await ticket.save();
    } else {
      return await memoryStore.createTicket({
        ticketId,
        customerId: data.customerId || 'CUST-DEMO-01',
        customerName: data.customerName || 'Alex Mercer',
        customerEmail: data.customerEmail || 'alex.mercer@example.com',
        category: data.category,
        priority: data.priority,
        title: data.title,
        description: data.description,
        summary: data.summary,
        department,
        status: 'Open',
        escalationStatus,
        recommendedAction: data.recommendedAction || 'Review issue details and verify with backend systems.',
        extractedEntities: data.extractedEntities,
        timeline,
      });
    }
  }

  /**
   * Retrieves all tickets with optional filtering and keyword search
   */
  public static async getTickets(filters: {
    category?: string;
    priority?: string;
    status?: string;
    search?: string;
  }) {
    if (isMongoConnected) {
      const query: any = {};
      if (filters.category && filters.category !== 'All') query.category = filters.category;
      if (filters.priority && filters.priority !== 'All') query.priority = filters.priority;
      if (filters.status && filters.status !== 'All') query.status = filters.status;
      if (filters.search) {
        query.$or = [
          { ticketId: { $regex: filters.search, $options: 'i' } },
          { title: { $regex: filters.search, $options: 'i' } },
          { customerName: { $regex: filters.search, $options: 'i' } },
          { summary: { $regex: filters.search, $options: 'i' } },
        ];
      }
      return await Ticket.find(query).sort({ createdAt: -1 });
    } else {
      let tickets = await memoryStore.getTickets();
      if (filters.category && filters.category !== 'All') {
        tickets = tickets.filter((t) => t.category === filters.category);
      }
      if (filters.priority && filters.priority !== 'All') {
        tickets = tickets.filter((t) => t.priority === filters.priority);
      }
      if (filters.status && filters.status !== 'All') {
        tickets = tickets.filter((t) => t.status === filters.status);
      }
      if (filters.search) {
        const s = filters.search.toLowerCase();
        tickets = tickets.filter(
          (t) =>
            t.ticketId.toLowerCase().includes(s) ||
            t.title.toLowerCase().includes(s) ||
            t.customerName.toLowerCase().includes(s) ||
            t.summary.toLowerCase().includes(s)
        );
      }
      return tickets;
    }
  }

  /**
   * Find a single ticket by ticketId (e.g. CS-2026-10482) or database ID
   */
  public static async getTicketById(id: string) {
    if (isMongoConnected) {
      return (await Ticket.findOne({ ticketId: id })) || (await Ticket.findById(id).catch(() => null));
    } else {
      return await memoryStore.getTicketById(id);
    }
  }

  /**
   * Updates ticket fields (status, department, priority) and adds a timeline log
   */
  public static async updateTicket(
    id: string,
    updates: {
      status?: TicketStatus;
      department?: string;
      priority?: TicketPriority;
      recommendedAction?: string;
      escalationStatus?: EscalationStatus;
      performedBy?: string;
      note?: string;
    }
  ) {
    const performedBy = updates.performedBy || 'Support Specialist';
    const event =
      updates.escalationStatus === 'Escalated'
        ? 'Ticket escalated to human specialist'
        : updates.status
        ? `Status changed to ${updates.status}`
        : updates.department
        ? `Department reassigned to ${updates.department}`
        : updates.priority
        ? `Priority updated to ${updates.priority}`
        : 'Ticket updated';

    const timelineEntry = {
      timestamp: new Date(),
      event,
      performedBy,
      note: updates.note || '',
    };

    if (isMongoConnected) {
      const ticket = (await Ticket.findOne({ ticketId: id })) || (await Ticket.findById(id).catch(() => null));
      if (!ticket) return null;

      if (updates.status) ticket.status = updates.status;
      if (updates.department) ticket.department = updates.department;
      if (updates.priority) ticket.priority = updates.priority;
      if (updates.recommendedAction) ticket.recommendedAction = updates.recommendedAction;
      if (updates.escalationStatus) ticket.escalationStatus = updates.escalationStatus;
      ticket.timeline.push(timelineEntry);

      return await ticket.save();
    } else {
      return await memoryStore.updateTicket(id, {
        ...(updates.status && { status: updates.status }),
        ...(updates.department && { department: updates.department }),
        ...(updates.priority && { priority: updates.priority }),
        ...(updates.recommendedAction && { recommendedAction: updates.recommendedAction }),
        ...(updates.escalationStatus && { escalationStatus: updates.escalationStatus }),
        timelineEntry,
      });
    }
  }

  /**
   * Escalates a ticket to a human support specialist
   */
  public static async escalateTicket(id: string, reason?: string, escalatedToDepartment?: string) {
    const department = escalatedToDepartment || 'Escalations & Incident Response';
    const note = reason || 'Customer requested human intervention or issue crossed automated threshold.';

    return await this.updateTicket(id, {
      department,
      status: 'Processing',
      escalationStatus: 'Escalated',
      performedBy: 'Human Escalation Engine',
      note: `Escalated: ${note}`,
    });
  }

  /**
   * Adds customer feedback to a ticket
   */
  public static async addFeedback(ticketId: string, rating: number, comment: string, customerName?: string) {
    if (isMongoConnected) {
      const fb = new Feedback({ ticketId, rating, comment, customerName });
      return await fb.save();
    } else {
      return await memoryStore.addFeedback(ticketId, rating, comment, customerName);
    }
  }

  /**
   * Retrieves dashboard statistics
   */
  public static async getDashboardStats() {
    if (isMongoConnected) {
      const totalTickets = await Ticket.countDocuments();
      const openTickets = await Ticket.countDocuments({ status: { $in: ['Open', 'Processing'] } });
      const highPriorityTickets = await Ticket.countDocuments({ priority: { $in: ['High', 'Critical'] } });
      const resolvedTickets = await Ticket.countDocuments({ status: { $in: ['Resolved', 'Closed'] } });
      const escalatedTickets = await Ticket.countDocuments({
        escalationStatus: { $in: ['Escalated', 'Human Specialist Assigned'] },
      });

      const recentTickets = await Ticket.find().sort({ createdAt: -1 }).limit(10);
      const feedbacks = await Feedback.find().sort({ createdAt: -1 }).limit(5);

      const allFeedbacks = await Feedback.find();
      const avgRating =
        allFeedbacks.length > 0
          ? Number((allFeedbacks.reduce((acc, f) => acc + f.rating, 0) / allFeedbacks.length).toFixed(1))
          : 4.9;

      return {
        totalTickets,
        openTickets,
        highPriorityTickets,
        resolvedTickets,
        escalatedTickets,
        avgRating,
        totalFeedback: allFeedbacks.length,
        recentTickets,
        feedbacks,
      };
    } else {
      return await memoryStore.getDashboardStats();
    }
  }
}
